name = "GongBetaAdrenergicSignaling"
uuid = "c9319e42-2a68-4d31-a4ce-d28d39ea7682"
version = "0.0.1"
authors = ["Kyle Beggs <beggskw@gmail.com> and contributors"]

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
ModelingToolkit = "9,10"
Reexport = "1.2"
julia = "1.10"
