name = "GongBetaAdrenergicSignaling"
uuid = "c9319e42-2a68-4d31-a4ce-d28d39ea7682"
version = "0.0.1"
authors = ["Kyle Beggs <beggskw@gmail.com> and contributors"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
CairoMakie = "0.15.6"
ModelingToolkit = "9"
OrdinaryDiffEq = "6"
Symbolics = "6"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
